### ISSUE TITLE
Breaking Lines

### ISSUE THREAD

**Issue by SybelBlue** [ace-lab/pl-ucb-faded-parsons#16]
[These lines](https://github.com/ace-lab/pl-ucb-faded-parsons/blob/9fddb65d2c2ec244cd52d215f4fadccae2915483/elements/pl-faded-parsons/pl-faded-parsons.py#L91-L99) are the crux of the crashing issue:
```
Traceback (most recent call last):
   ...
  File "/course/elements/pl-faded-parsons/pl-faded-parsons.py", line 159, in render
    return render_question_panel(element_html, data)
  File "/course/elements/pl-faded-parsons/pl-faded-parsons.py", line 94, in render_question_panel
    "code_lines" : read_file_lines(data, QUESTION_CODE_FILE) 
  File "/course/elements/pl-faded-parsons/pl-faded-parsons.py", line 30, in read_file_lines
    raise e
  File "/course/elements/pl-faded-parsons/pl-faded-parsons.py", line 26, in read_file_lines
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 
   '/course/questions/polynomial_evaluation/serverFilesQuestion/code_lines.py'
...
```
It's unclear why these lines *always* overwrite the contents of the param `code_lines`, trashing the text of the element that was used before. 
In cases that do not use the pre-text/post-text/code-lines tags, the element text should suffice as in the example square_color question (at least for now - we should consider changing this soon).

**Comment by SybelBlue** [comment]
#18 fixes this
